import React, { FC } from 'react'
import styles from './index.module.scss'

const StatOverview: FC = () => {
  return (
    <div className={styles.main}>
      <div className={styles['stat-overview-wrapper']}>
        <div className={styles.test}>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
          <p>StatOverview</p>
        </div>
      </div>
    </div>
  )
}

export default StatOverview
